# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wonder &amp; Welcome
logo: /images/wonder-and-welcome-logo.png
email: info@reallyseth.com
description: "A podcast conversation about parenting and following Jesus, hosted by Seth and Shannon Hein."
subtitle: "A podcast about parenting and following Jesus."
lang: en-us
author: Seth Hein, Shannon Hein
copyright: "&#xA9; 2023"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.wonderandwelcome.com" # the base hostname & protocol for your site
twitter_username: reallyseth
github_username:  reallyseth

permalink: /:year/:title.html

#Timezone
timezone: North America/Chicago

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']