# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wonder & Welcome 
email: info@reallyseth.com
description: "This is a discussion between Seth and Shannon, and sometimes other friends."
subtitle: "A podcast about parenting and following Jesus."
lang: en-us
author: Seth Hein, Shannon Hein
copyright: "&#xA9; 2023"
baseurl: "/wonder-and-welcome-podcast" # the subpath of your site, e.g. /blog
url: "http://wonderandwelcome.com" # the base hostname & protocol for your site
twitter_username: reallyseth
github_username:  reallyseth

permalink: /:year/:title.html

#Timezone
timezone: North America/Chicago

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']