# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wonder &amp; Welcome
logo: /images/wonder-and-welcome-logo.png
email: info@reallyseth.com
description: "Parenting is hard! We know, we've been in the middle of it for over a decade. And we have needed a lot of help and encouragement along the way. That's why we wanted to create the <em>Wonder & Welcome</em> podcast. We've received so much help and support, we want to share some of that with you. We'd always appreciate your feedback and you can get in touch with us on <a href='mailto:info@reallyseth.com?subject=Wonder & Welcome Podcast'>email</a> and  or on <a href='http://instagram.com/reallyseth'>instagram</a>!"
subtitle: "A podcast about parenting and following Jesus."
lang: en-us
author: Seth Hein, Shannon Hein
copyright: "&#xA9; 2023"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.wonderandwelcome.com" # the base hostname & protocol for your site
twitter_username: reallyseth
github_username:  reallyseth

permalink: /:year/:title.html

#Timezone
timezone: North America/Chicago

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']